// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/about/topic": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/faq/react": {
    params: {};
  };
  "/faq/router": {
    params: {};
  };
  "/faq/*": {
    params: {
      "*": string;
    };
  };
  "/members": {
    params: {};
  };
  "/members/:userName": {
    params: {
      "userName": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/about" | "/about/topic" | "/faq" | "/faq/react" | "/faq/router" | "/faq/*" | "/members" | "/members/:userName" | "/*";
  };
  "pages/Home.tsx": {
    id: "pages/Home";
    page: "/";
  };
  "pages/contact/ContactPage.tsx": {
    id: "pages/contact/ContactPage";
    page: "/contact";
  };
  "pages/about/AboutPage.tsx": {
    id: "pages/about/AboutPage";
    page: "/about";
  };
  "pages/about/topic/topic.tsx": {
    id: "pages/about/topic/topic";
    page: "/about/topic";
  };
  "pages/faq/layout.tsx": {
    id: "pages/faq/layout";
    page: "/faq" | "/faq/react" | "/faq/router" | "/faq/*";
  };
  "pages/faq/FaqPage.tsx": {
    id: "pages/faq/FaqPage";
    page: "/faq";
  };
  "pages/faq/answers/react.tsx": {
    id: "pages/faq/answers/react";
    page: "/faq/react";
  };
  "pages/faq/answers/router.tsx": {
    id: "pages/faq/answers/router";
    page: "/faq/router";
  };
  "pages/faq/not-found.tsx": {
    id: "pages/faq/not-found";
    page: "/faq/*";
  };
  "pages/members/layout.tsx": {
    id: "pages/members/layout";
    page: "/members" | "/members/:userName";
  };
  "pages/members/index.tsx": {
    id: "pages/members/index";
    page: "/members";
  };
  "pages/members/members.tsx": {
    id: "pages/members/members";
    page: "/members/:userName";
  };
  "not-found.tsx": {
    id: "not-found";
    page: "/*";
  };
};