// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/faq": {
    params: {};
  };
  "/faq/react": {
    params: {};
  };
  "/faq/router": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/contact" | "/about" | "/faq" | "/faq/react" | "/faq/router" | "/*";
  };
  "pages/home.tsx": {
    id: "pages/home";
    page: "/";
  };
  "pages/contact/Page.tsx": {
    id: "pages/contact/Page";
    page: "/contact";
  };
  "pages/about/Page.tsx": {
    id: "pages/about/Page";
    page: "/about";
  };
  "pages/faq/layout.tsx": {
    id: "pages/faq/layout";
    page: "/faq" | "/faq/react" | "/faq/router";
  };
  "pages/faq/Page.tsx": {
    id: "pages/faq/Page";
    page: "/faq";
  };
  "pages/faq/answers/react.tsx": {
    id: "pages/faq/answers/react";
    page: "/faq/react";
  };
  "pages/faq/answers/router.tsx": {
    id: "pages/faq/answers/router";
    page: "/faq/router";
  };
  "not-found.tsx": {
    id: "not-found";
    page: "/*";
  };
};